### ISSUE TITLE
如何配置只需要的功能呢？

### ISSUE THREAD

**Issue by icarusion** [xuexb/github-bot#32]
比如只需要自动关闭 issue 的功能，不需要 pr 的，在哪里能配置呢？

**Comment by xuexb** [comment]
hi @icarusion ，这个仓库只是我用来测试回归 Github 机器人功能，也就是这里只是一种 show case ，具体应用到真实的项目里时，可能需要相应的调整。

如你说的只要自动关闭 issue 功能，这个需要有 issue 的规范，而自动关闭是基于这个规范自动匹配处理的。

具体代码在 `/src/modules/<type>/*.js` ，你可以根据自己需求相应的添加、删除~

感谢关注~

**Comment by icarusion** [comment]
ok, thanks :)
