### ISSUE TITLE
添加修改标题的功能

### ISSUE THREAD

**Issue by icarusion** [xuexb/github-bot#34]
想做一个对中文 issue 翻译为英文的功能，需要 bot 去改标题，并创建一个翻译后的 comment，目前 comment 是现成的了，就差修改标题

**Comment by xuexb** [comment]
hi, @icarusion 我的思路是：

1. `src/utils.js` 创建一个中文->英文的方法
2. `src/utils.js` 创建一个判断是否为中文的方法
2. `src/github.js` 创建一个修改 issue 标题的方法，调用的接口是： [node-github/#api-issues-edit](https://octokit.github.io/node-github/#api-issues-edit)
2. 创建 `src/modules/issue/translateEn.js` 监听 `issues_opened` 事件，判断当前  issue ：
    1. 标题为中文，转英文并调用修改标题方法
    2. 内容为中文，转英文并调用评论方法

要考虑的是：

1. 只是针对创建 issue 时才转英文吗？如果用户再编辑 issue 标题和内容呢？如果编辑也处理，就要考虑死循环问题了，因为机器人也是会触发编辑事件
2. issue 内如果再有新评论是否转英文呢

**Comment by yugasun** [comment]
@icarusion @xuexb 我觉得如果是想做一个英文的robot，不如直接从源头限制吧，`直接限制用户使用某种通用语言来进行所有操作`。

为什么这么说呢，首先是@xuexb 上面提到的问题，其次机器翻译(比如google翻译)，用过的都知道，那些英文翻译有时很蹩脚，还不如认为翻译，因此这个feature，个人觉得没必要。

**Comment by icarusion** [comment]
折腾了半天，已经实现了，效果还行，就是对 markdown 的处理还不太好
https://github.com/iview/iview/issues/2281

**Comment by xuexb** [comment]
@icarusion 👍 ，<https://www.iviewui.com/docs/guide/introduce> 底部的 提交bug 是不是得更新下~

**Comment by icarusion** [comment]
是的，已修改
