### ISSUE TITLE
关于不依赖github hook测试方案的讨论

### ISSUE THREAD

**Issue by yugasun** [xuexb/github-bot#42]
@xuexb @ddhhz

**Comment by ddhhz** [comment]
不依赖 github hook 如何测试功能嘞，比如自动回复，自动关issue，自动添加tag，之类的？

可以用 `npm i ngrok -g; ngrok http 8080` 或 Cloudflare Wrap 等工具进行内网穿透，然后更改 github hook 为其地址直接指向开发机进行测试。

**Comment by xuexb** [comment]
我想的是，这个测试就做成基于 [mocha](http://mochajs.org/) 的单元测试吧。如 `src/modules/issue/autoLabel.js` 是自动打 label 的，那么，我们在 `test/modules/issue/autoLabel.js` 中使用 github webhooks 中的完整的代码，复制到 test 文件中，用来做为 mock payload ，当然这个数据得来自真实的 github webhooks ，然后使用 [sinonjs](http://sinonjs.org/) 拦截/模拟 `addLabelsToIssue` 达到自动化测试的目的。

你们觉得呢？

当然这个层面只是相对保障了代码的稳定性，具体还是真实的和 github 交互验证更安全。

**Comment by yugasun** [comment]
我的想法跟@xuexb你的差不多，基于mocha/jest之类的测试工具，然后根据github-bot的相关功能，模拟对应hook payload，进行结果验证。

**Comment by ddhhz** [comment]
嗯 自动化单元测试可以这样处理。开发时手动测试就可以用我说的方法。

**Comment by xuexb** [comment]
赞。那我就开搞了啊，哈哈哈~

**Comment by yugasun** [comment]
@xuexb 干吧得~
