### ISSUE TITLE
如何以bot的名义处理issue

### ISSUE THREAD

**Issue by luisliuchao** [xuexb/github-bot#51]
想问一下怎么设置可以让新创建的bot账号在自己的repo里面处理issue？ 
我可以用自己的github的token，但是会以我本人的名义处理issue。如果用bot的token，github会报错：Must have admin rights to Repository

**Comment by xuexb** [comment]
hi @luisliuchao ，需要在对应项目设置（`https://github.com/owner/repo/settings/collaboration`）里添加 bot ，让 bot 具有操作项目的权限。

感谢提醒，我在文档里也加下对应的说明吧。

**Comment by luisliuchao** [comment]
@xuexb 还有一个问题，需要给bot token多少权限？

**Comment by xuexb** [comment]
@luisliuchao 由于主要是针对项目的操作，给 `repo` 权限吧。

并且推荐看下 https://github.com/xuexb/github-bot/issues/45 ，想后续做成一个 bot 对应多个仓库，看你有什么想法不~

**Comment by luisliuchao** [comment]
@xuexb 好的！加了collaborator就可以啦！
